### PR TITLE
added link to webpack config tool for react apps

### PR DESCRIPTION
**Pull request by jakoblind**

### CODE REVIEW

**Comment by Haroenv** [comment]
thanks! this should probably go at the end of the list though, they're sorted by date of addition :)

**Comment by Haroenv** [comment]
oh and the link probably should be the GitHub project (less likely to go down) https://github.com/jakoblind/webpack-autoconf

**Comment by jakoblind** [comment]
Sure! I made a new commit.

**Comment by Haroenv** [comment]
perfect!

**Pull request merged**
