### PR TITLE
Add react-magic-move to components

### PR DESCRIPTION
**Pull request by andrewkhan1**
This uses portals to animate React.js DOM changes by using JavaScript portals. It's especially effective with position changes. This is an effect that is easily done with React, with the introduction of the virtual DOM. 

Please see the below video for why react-magic-move is great.

https://youtu.be/z5e7kWSHWTg?t=9m36s

### CODE REVIEW

**Comment by zzz6519003** [comment]
this one's awesome! love u!

**Comment by andrewkhan1** [comment]
Yeah, it's pretty cool. Definitely check the rest of that video too, gets you real hyped for React ;)

**Comment by zzz6519003** [comment]
seeing the code, wondering where the "transition" in css coms from XD

**Comment by andrewkhan1** [comment]
From what I understand this is essentially what it does:

1. Moves the markup off the page into a 'javascript portal'. 
2. Replicates the markup in the visible DOM using absolute positioning to replicate flow
3. DOM changes are made in the off-page portal and information on positioning is passed to the visible DOM's absolute position
4. You can now animate the position using transitions
5. Success!

**Comment by andrewkhan1** [comment]
Also see the README.md for an example of the CSS

**Pull request merged**
