### PR TITLE
FEATURE: Add 'React and TypeScript' tutorials

### PR DESCRIPTION
**Pull request by JamesAlias**
Add (kick)starter guides for TypeScript-React projects.
Provided links:

* https://github.com/Microsoft/TypeScript-React-Starter
* https://sandstorm.github.io/typescript-react-app-kickstart-guide/
* https://basarat.gitbooks.io/typescript/docs/jsx/react.html (thanks @Haroenv )

Removed boken links:
* https://fistfulofbytes.com/graphql-and-g2sd/  (gets 502)
* https://learn.pusher.com/rpg (broken certificate)

### CODE REVIEW

**Comment by Haroenv** [comment]
https://basarat.gitbooks.io/typescript/docs/jsx/react.html also comes up quite high in google, do you think it should be added too?

**Comment by Haroenv** [comment]
thanks for removing the broken ones, was going to do that after your PR

**Comment by JamesAlias** [comment]
Is there anything preventing this PR from being merged? If so, let me know or just close the PR if it's changes are not wanted 😉

**Comment by Haroenv** [comment]
nope this is fine :) feel free to add more to make that category bigger!

**Pull request merged**
