### PR TITLE
Add boilerplate, markdown with React, redux+react for beginners

### PR DESCRIPTION
**Pull request by Romathonat**
Add boilerplate(react+redux+semantic UI), markdown with React, redux+react for beginners

### CODE REVIEW

**Comment by browniefed** [comment]
This is failing because we do not allow duplicate links, if you want to include duplicate links you need to include them in this file https://github.com/enaqx/awesome-react/blob/master/.travis.yml

**Comment by Romathonat** [comment]
Thank you for you reponse, but can't see where there is a duplicate link ! #490 seems to have the same problem, if I look at the error with travis i see : 

```
Issues :-(

> Links 

  1. [L0305] 503 http://react-components.com/  
```
And this link seems dead indeed

**Comment by browniefed** [comment]
@Romathonat ah sorry I saw the `vulgairedev` links and thought they were the same link and that's why it was failing, sorry about that.

**Comment by Romathonat** [comment]
No problem ;)

**Pull request merged**
