### PR TITLE
add JSXZ, the HTML to JSX macro language

### PR DESCRIPTION
**Pull request by awetzel**

### CODE REVIEW

**Comment by awetzel** [comment]
Sorry to ask :) but this doesn't even deserve a comment ?

**Comment by enaqx** [comment]
Ouch, sorry. No offense.  I'm gonna clean this list from lot of things and leave only well-established common used modules and references. It becomes quite overfilled.

**Comment by awetzel** [comment]
Yes I understand :) . IMHO some of the most useful modules for React are not yet well-established because of the youthfulness of the ecosystem, and some of the most common used modules are already outdated. So I think your own experiences and feelings about the libs are more important criteria than the current usage inside the community. 
Still, not easy to make choices.
No offense at all

**Comment by enaqx** [comment]
@awetzel Agree. But I'm still thinking this list is kinda overwhelmed and not filled in pattern of `best resources distilled. I've started this as collection of different resources for my own convenience for development activity. Since it became little popular I cannot really examine quality of all resources properly due to lack of time.

**Pull request merged**
