### PR TITLE
Add in my tutorials from my blog

### PR DESCRIPTION
**Pull request by browniefed**

### CODE REVIEW

**Comment by enaqx** [comment]
Thanks!

**Comment by browniefed** [comment]
@enaqx is it possible to get commit access, I'd love to help keep this up to date. Lot of good stuff out there, would like this to be the best resource.

**Comment by enaqx** [comment]
@browniefed Great. I've added you to collaborators.

**Comment by browniefed** [comment]
@enaqx awesome, thank you, hopefully I can get some time this weekend. I co-maintain ReactJSNews, so I need to work on a re-tweet hook and PR to here :)

**Pull request closed without merging**
