### PR TITLE
Add JSX Loader

### PR DESCRIPTION
**Pull request by ConradSollitt**

### CODE REVIEW

**Comment by Haroenv** [comment]
interesting idea, but I think the link could break in the future if you change, is there something more permanent? Would you also update the description to be more like the other ones?

**Comment by ConradSollitt** [comment]
Thanks for the fast response Haroenv!

What would you think of one of these descriptions:
* _Small JavaScript Compiler for including JSX with React directly on a web page_
* _Small JavaScript Compiler for quickly converting JSX to JS directly on a web page_

Or would you have another suggestion?

The link will definitely not break in the future and is the permanent link for it. The main project readme includes additional content while this page is the focused link for JSX Loader. I’ve shared this link with Reddit, Hacker News, and other developers so I wouldn’t break it for that reason alone.

**Comment by Haroenv** [comment]
The second description seems best to me, thanks!

**Comment by ConradSollitt** [comment]
Done! Thanks for your suggestions and help! :+1:

**Pull request merged**
