### PR TITLE
Add Component react-listview-sticky-header

### PR DESCRIPTION
**Pull request by cht8687**

### CODE REVIEW

**Comment by browniefed** [comment]
Hi, could you please rebase or open a new request to manage the conflict. Thank you

**Comment by cht8687** [comment]
thank. please delete this pull request. I will do anther PR.

**Comment by cht8687** [comment]
sorry to send so many 'unused' PR... possible to delete them? @browniefed

**Comment by browniefed** [comment]
Closing them is good enough

**Pull request closed without merging**
