### PR TITLE
Add awesome badge.

### PR DESCRIPTION
**Pull request by appleboy**
https://github.com/sindresorhus/awesome/issues/253

### CODE REVIEW

**Comment by appleboy** [comment]
ping @enaqx

**Comment by jhabdas** [comment]
Feels gimmicky. Is there [a bar](http://habd.as/react-resources/) to being awesome?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/master/awesome.md

**Comment by enaqx** [comment]
Thanks for including! I'll try to keep list with relevant links only since people refer to this as source of info.

**Comment by jhabdas** [comment]
This list is officially awesome now.

**Pull request merged**
