### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by viczam**

### CODE REVIEW

**Comment by enaqx** [comment]
Sorry, It's non-free information.

**Comment by viczam** [comment]
I know, but neither this one is free - http://shop.oreilly.com/product/9781939902122.do

**Comment by enaqx** [comment]
You are right. I will delete all this section.

**Comment by viczam** [comment]
I think you shouldn't. I'm not affiliated in any way with the book from leanpub, but I think it worths linking to paid courses / books etc.

For example, pluralsight has a course about react (a bit outdate though) - http://www.pluralsight.com/courses/react-fundamentals

**Comment by enaqx** [comment]
@viczam  I do not blame you in product placement, of course :smile_cat: 

I think it's OK if somebody sell their knowledge and experience. But i would like to add here reference to some stuff I can explore by myself.

**Comment by enaqx** [comment]
2c20c99906ef35327cea1a43650681fa6aa397d0

**Pull request closed without merging**
