### PR TITLE
added animate-components

### PR DESCRIPTION
**Pull request by nitin42**
`animate-components` - Elemental components for animations in React.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Does this belong under Libraries or Components?

**Comment by nitin42** [comment]
Yes!

**Comment by paulmelnikow** [comment]
Which one though?

**Comment by nitin42** [comment]
Oh sorry! Yeah, under library.

**Comment by paulmelnikow** [comment]
Could you explain your reasoning? After taking a quick look at it, I'm not sure I understand why.

**Pull request closed without merging**
