### PR TITLE
add redux tutorials and boilerplate

### PR DESCRIPTION
**Pull request by mz026**

### CODE REVIEW

**Comment by browniefed** [comment]
Some other things have been merged, could you please rebase so this can be merged?
Thank you

**Comment by mz026** [comment]
Sure! I've rebased it, thanks!

**Comment by browniefed** [comment]
Well I merged something else and it caused more conflicts :(. I hate to ask you to rebase again, but could you. Trying to get the PRs to 0 and all these merges keep causing conflicts.

**Comment by mz026** [comment]
ha! No problem, thanks!

**Comment by browniefed** [comment]
Thanks!

**Pull request merged**
