### PR TITLE
Add Prerendering section

### PR DESCRIPTION
**Pull request by stereobooster**

### CODE REVIEW

**Comment by stereobooster** [comment]
> Can you add something about Gatsby

To be sure - Gatsby is another approach, it is static site generator. Another example of static site generators: phenomic, react-static. In case of static site generator, you are locked to conventions of the solution you choose. And yes - Gatsby is great.

> next

I prefer Razzle

> native ssr?

What do you mean? There is already a big section about `Server Side rendering`.

In case you are interested in different prerenderes, here is [my comparison](https://github.com/stereobooster/react-snap/blob/master/doc/alternatives.md)

**Comment by Haroenv** [comment]
Could you still add some others to your section, it looks a bit weird to have a section with just one entry :)

**Comment by Haroenv** [comment]
Happy new year soon

**Comment by stereobooster** [comment]
> it looks a bit weird to have a section with just one entry

This is [Awesome](https://github.com/sindresorhus/awesome) project. It is about awesome stuff. If there is only one awesome thing of the type there will be only one item on the list. There is nothing weird about. Not saying this the case, but the argument is wrong.

> Could you still add some others to your section,

I'm adding things that I can recommend. If somebody else feels like they want to add something else they are welcome.

Happy new year

**Comment by Haroenv** [comment]
Perfect 👌, sorry if I came over wrong

**Comment by stereobooster** [comment]
Everything is ok. No worries :)

**Comment by paulmelnikow** [comment]
👍 

Could you add that comparison link too? It seems to put things in context.

**Comment by stereobooster** [comment]
@pauldotknopf done

**Pull request merged**
