### PR TITLE
Add react-tsx-starter to Boilerplates section

### PR DESCRIPTION
**Pull request by toddlucas**
I've been working to keep this current, including adding a Redux branch. It was just updated to React Router 2.0 as well. Thanks.

### CODE REVIEW

**Comment by browniefed** [comment]
Some other things have been merged, could you please rebase so this can be merged?
Thank you

**Comment by toddlucas** [comment]
I just rebased. Hopefully it's good now. Thanks.

**Comment by browniefed** [comment]
Looks like you merged master into the branch instead, bringing a lot of existing commits in master. Can you possibly fix this?

**Comment by toddlucas** [comment]
Why don't we close this and I'll submit another PR?

**Comment by browniefed** [comment]
That sounds good

**Pull request closed without merging**
