### PR TITLE
Added bulletproof-react

### PR DESCRIPTION
**Pull request by moshfiqrony**
Created a new section for **React Project Architecture Tools** and added a new package **bulletproof-react** under the section

### CODE REVIEW

**Comment by alan2207** [comment]
Hi @moshfiqrony, thanks for adding bulletproof-react repo to the list I appreciate it. 

I must add that it is not a package or a tool, but a collection of good practices and architectural choices when creating a react app with an application that showcases everything in a practical way included. I would suggest you move it outside the tools section and place it under `React Architecture` section instead.

Thanks again! :)

**Comment by moshfiqrony** [comment]
Thanks @alan2207 .I am doing it

**Comment by moshfiqrony** [comment]
I have changed the section @alan2207 . Thanks for the great contribution of yours. I will also try to contribute on that repo

**Comment by enaqx** [comment]
Thank you, Since I have significantly cleaned React tutorials section, I will put it under general recommended section since it is worth to read for advanced React devs.

**Pull request closed without merging**
