### PR TITLE
Add react-ui-cards to components

### PR DESCRIPTION
**Pull request by nukeop**
Ready to use card UI components.

A demo can be found here: https://nukeop.github.io/react-ui-cards/

### CODE REVIEW

**Comment by Haroenv** [comment]
Hey @nukeop, I think there's a performance bottleneck in this library, it lags when I scroll the demo. Could you take a look at that first?

**Comment by nukeop** [comment]
Thanks for the quick response.

I checked with a profiler but couldn't find anything out of the ordinary. I'm using only CSS animations which should be hardware-accelerated. The only re-renders that occur are when you click the arrows in the mini carousel in the product cards. Do you have any pointers where to look?

**Comment by Haroenv** [comment]
It's actually the filter: blur which was causing really bad performance on scroll on my machine. 

Otherwise I also notice that you could put a timeout on the starting of the flip animation, otherwise you'll get fiddly "mouse over card / mouse not over card anymore because the card is smaller now" animations

**Comment by nukeop** [comment]
Thanks for the advice, I tried mitigating the issues with blur and fixed the flipping card animation issue.

**Pull request merged**
