### PR TITLE
Add Coflux and MobX to Flux implementations list.

### PR DESCRIPTION
**Pull request by blainekasten**
Two new flux libraries have came out recently, simply adding them to the flux list.

### CODE REVIEW

**Comment by brillout** [comment]
Hi!

Interesting.

I'm curious, are you aware of other data managing libraries that try to achieve that?

I like the idea of having the components define their part of the store. Why not pushing the idea so far as to get rid of a central store? Your library would internally create the central store by composing what the components have defined. 

Some feedbacks about details;

 - `App state is simply a dependency of your components.` I don't understand this sentence

 - `new performance benefits previously not possible.` How is that?

 - Why not naming `mapStateToProps` to  `mapStoreToProps`?

 - The code snippets have several variables that are undefined. It would make it easier to read if all variables/functions are defined within the code snippets.

As for MobX: it is already added under the `Data Managing` section.

**Comment by blainekasten** [comment]
@brillout Thanks for the feedback! I've been looking for this sort of feedback. I'll do my best to answer your questions.

> Why not pushing the idea so far as to get rid of a central store? Your library would internally create the central store by composing what the components have defined.

That was my original goal of the project. The problem I ran into is needing to "bootstrap" or default data. It made sense to just let the users build the store, but then that created the fragility of making your store shape match your path selectors. I would still love to get to the point where the store is removed. I just need to think of a good way to bootstrap or default data. If you have any ideas i'd gladly be interested.

> `App state is simply a dependency of your components.` I don't understand this sentence

Maybe i'm trying to get too buzz-wordy. But effectively, it's just saying that your application state is a dependency of your components. Maybe that's not specific to coflux, I guess nearly every react app would do nothing without "app state." Good feedback. Probably need to rethink that one.

> `new performance benefits previously not possible.` How is that?

This is done primarily through the use of `path`s. I am being generous by saying "previously not possible." Probably should be re-worded. It's not saying these things were not possible, and possibly are already done. The performance benefits are that coflux manages `shouldComponentUpdate` for you behind the scenes with cheap comparison checks. Not expensive object walking checks. Since we have "paths" that signify state locations, i can easily know if a component will need an update based on what "path" was changed in state.

> Why not naming `mapStateToProps` to `mapStoreToProps`?

I'm not opposed to that. I was also considering changing it to `observeState` as it does do a sort of observation-like flow. https://github.com/blainekasten/coflux/issues/18

> The code snippets have several variables that are undefined. It would make it easier to read if all variables/functions are defined within the code snippets.

Deal. I'll work on that.

**Comment by Haroenv** [comment]
Hey @blainekasten, do you still want this in?

**Comment by blainekasten** [comment]
@Haroenv lol sure, why not. I'm haven't paid much attention to that project in a while as it didn't catch much steam. But maybe being here would help people see the project and validate or invalidate the idea of it.

**Comment by Haroenv** [comment]
perfect then 👌

**Pull request merged**
