### PR TITLE
Adding in several React Tutorials and a demo app link

### PR DESCRIPTION
**Pull request by jakelumetta**
Recently came across this Awesome list 😄 .  These articles are written by members of the React community to help other React devs get things done, learn best practices and new tips and tricks.

### CODE REVIEW

**Comment by jakelumetta** [comment]
Hi - just wanted to follow up on this.

**Comment by jakelumetta** [comment]
Hello - who's the best person to have review this PR?  Cheers!

**Comment by moluwole** [comment]
These are actually nice articles!!!!

**Comment by jakelumetta** [comment]
@Haroenv mind taking a look at this one?

**Pull request closed without merging**
