### PR TITLE
Add SurveyJS Library

### PR DESCRIPTION
**Pull request by andrewtelnov**
Probably the most advanced Survey/Form Library at the current moment under MIT license, that has version for react.

### CODE REVIEW

**Comment by andrewtelnov** [comment]
@enaqx Is it anything wrong with our Github mono repo? 
We have a platform independent part, in the [root](https://github.com/surveyjs/survey-library/tree/master/src)  and several versions for different platforms. We wrote the react version correctly. [Here the react code](https://github.com/surveyjs/survey-library/tree/master/src/react). Here is [survey-react npm](https://www.npmjs.com/package/survey-react).

Thank you,
Andrew

**Comment by enaqx** [comment]
@andrewtelnov 

Thanks, Andrew

The library is OK, no worries, but
 * it is the general library, not React specific
 * it is part of your paid product, which is absolutely OK in general, but not for this list

Here we tend to include completely free libraries.

**Comment by andrewtelnov** [comment]
@enaqx The library itself is free, under MIT license. We do have [Survey Creator](https://github.com/surveyjs/survey-creator), that it is not free. You need it, if you want your users/customers to create surveyjs on your web site/app. The most people just do not need it. You may create survey definition on [our website](https://surveyjs.io/create-survey/), free and without registration or, as many users do, just write survey definition json in a text file.
Anyway, I would not insists. That is your repo and your rules :-)

Thank you,
Andrew

**Comment by enaqx** [comment]
Thanks for understanding. 

You can try to add to https://github.com/brillout/awesome-react-components.

**Comment by andrewtelnov** [comment]
@enaqx Thank you!
Andrew

**Pull request closed without merging**
