### PR TITLE
Add WTFlux to the list of Flux Implementations

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by enaqx** [comment]
Sorry, Flux list os overloaded. :mushroom:

**Comment by xgrommx** [comment]
@enaqx Why you merged pull request from @gaearon but don't want do it for @staltz? Because both pull requests were published on the same time.

**Comment by staltz** [comment]
Oh, really? I didn't see that https://github.com/enaqx/awesome-react/pull/183
I thought the list was overloaded? My PR came in before his by the way.

**Comment by xgrommx** [comment]
I agree with you @staltz. It isn't friendly

**Comment by enaqx** [comment]
Because Redux is older. If you need your Flux implementation in this damn list, just ping me next month or two. If it is accepted by community I will add it. It's not the list of all Flux implementations, just most used ones. Thanks. And no offense guys. :hand:

**Comment by staltz** [comment]
Ok, I'll ping you next month. ;)

**Comment by staltz** [comment]
@enaqx what did you mean with "accepted by the community"? I don't believe it's purely the number of GitHub stars. But if that's the issue, WTF now has 36 stars, and also a tweet by vjeux:

https://twitter.com/Vjeux/status/615191651456303104

How about reopening this PR and merging it? It means a lot to me, and come on, it's just one more Flux on this list.

**Comment by gaearon** [comment]
I think at the very least you need to have a TodoMVC example. An empty repo with a TODO: write TODO might work here..

**Comment by gaearon** [comment]
That would make it the first Flux library to feature a higher order TodoMVC example.

**Comment by staltz** [comment]
:+1: will do

**Comment by gaearon** [comment]
@staltz I sent a PR!

**Comment by enaqx** [comment]
Added. Thanks @staltz

**Pull request closed without merging**
