### PR TITLE
add `typesafe-i18n` to list

### PR DESCRIPTION
**Pull request by ivanhofer**

### CODE REVIEW

**Comment by ivanhofer** [comment]
Any words on why this was not merged?

**Comment by enaqx** [comment]
Sure, We already have [react-i18next](https://github.com/i18next/react-i18next) and since I want significantly clean this list I do not have plan to create separate section on i18n. It is great project but is not directly connected specifically to React.

**Comment by enaqx** [comment]
Actually I think it worths to create React i18n section and your lib is amazing fit. Thank you!

**Comment by ivanhofer** [comment]
Thank you!

**Pull request closed without merging**
