### PR TITLE
Added some great tutorials and resources for React, Flux and API Integration

### PR DESCRIPTION
**Pull request by tonyspiro**

### CODE REVIEW

**Comment by browniefed** [comment]
Please rebase so this can be merged

**Comment by tonyspiro** [comment]
Done :+1:

**Comment by browniefed** [comment]
Thanks, everything looks good.

**Comment by tonyspiro** [comment]
Oops, looks like I missed something... doing another pull

**Comment by browniefed** [comment]
heh, no worries, thanks for you contributions

**Pull request merged**
