### PR TITLE
Add React-Native Starter App - Parse.com, Redux, Jest, Immutable (88% coverage)

### PR DESCRIPTION
**Pull request by bartonhammond**
I've released an 𝐎𝐩𝐞𝐧 𝐒𝐨𝐮𝐫𝐜𝐞 𝐒𝐨𝐟𝐭𝐰𝐚𝐫𝐞 project I call 𝑺𝒏𝒐𝒘𝒇𝒍𝒂𝒌𝒆. It's a javascript based application for both iOS and Android Devices. It is written using 𝗥𝗲𝗮𝗰𝘁𝗡𝗮𝘁𝗶𝘃𝗲, 𝗣𝗮𝗿𝘀𝗲.𝗰𝗼𝗺, 𝗥𝗲𝗱𝘂𝘅, 𝗝𝗲𝘀𝘁, 𝗜𝗺𝗺𝘂𝘁𝗮𝗯𝗹𝗲, and other technologies. This release it to help other developers learn how these 𝘁𝗲𝗰𝗵𝗻𝗼𝗹𝗼𝗴𝗶𝗲𝘀 𝘄𝗼𝗿𝗸 𝘀𝗲𝗮𝗺𝗹𝗲𝘀𝘀𝗹𝘆 𝘁𝗼𝗴𝗲𝘁𝗵𝗲𝗿 and take what used to be incredibly difficult to now be very achievable. I would consider it at this time as a "𝗯𝗼𝗶𝗹𝗲𝗿𝗽𝗹𝗮𝘁𝗲" or "𝘀𝘁𝗮𝗿𝘁𝗲𝗿" project that developers can learn from and use as their starting point

### CODE REVIEW

**Comment by zzz6519003** [comment]
awesome job

**Comment by bartonhammond** [comment]
Thanks.  And thanks for this list - I referred to it numerous times

**Comment by browniefed** [comment]
@bartonhammond thanks for snowflake, actually having a good Jest mock to send people to for RN mocking is the best!

**Comment by bartonhammond** [comment]
@zzz6519003 @browniefed Thanks - I wanted to do something more complex then Todos while still keeping it succinct so that folks can wrap their head around it.  I'm happy there's interest.

**Pull request merged**
