### PR TITLE
Add react-redux-starter-kit (zero build config)

### PR DESCRIPTION
**Pull request by cloudmu**
A react starter-kit (boilerplate), newly ported to use create-react-app.

### CODE REVIEW

**Comment by brillout** [comment]
:+1:

Jwt sounds interesting. A description about how JWT works and how it is used in `react-redux-starter-kit` would be nice!

**Comment by cloudmu** [comment]
JWT based API server is added back, thanks to the latest create-react-app feature [Proxying API Requests](https://github.com/facebookincubator/create-react-app/blob/ef94b0561d5afb9b50b905fa5cd3f94e965c69c0/template/README.md#proxying-api-requests-in-development).

JWT related code is well documented in the source code.  Readme has links to JWT resources.

**Comment by enaqx** [comment]
There are tons of starter kits. We have already overbloated Boilerplates section. I would recommend anyone just stick to create-react-app.

**Comment by cloudmu** [comment]
I probably should have picked a better name. The project goes beyond typical starter kits, by balancing simplicity with developing a real SPA with authentication (JWT), navigation, server notifications, async data fetching, caching and pagination.

CRA takes care of `build`.

**Pull request closed without merging**
