### PR TITLE
Add React ESI

### PR DESCRIPTION
**Pull request by dunglas**
Add the React ESI libary: https://github.com/dunglas/react-esi

> React ESI is a super powerful cache library for vanilla React and Next.js applications, that can make highly dynamic applications as fast as static sites.

### CODE REVIEW

**Comment by enaqx** [comment]
Seems like it is not under active development at the moment.

**Comment by dunglas** [comment]
@enaqx it is! Has it works pretty well and is used on several bug websites I production without issues, it just doesn’t require many commits to maintain.

**Comment by enaqx** [comment]
@dunglas Ok, then. I have included it in the libraries section. Thanks a lot!

**Comment by dunglas** [comment]
Thanks!

**Pull request closed without merging**
