### PR TITLE
added react-based ComingOrNot project to Example Apps

### PR DESCRIPTION
**Pull request by lakshmantgld**
ComingOrNot - an event planner based on react, react-router, redux, graphQL and serverless

### CODE REVIEW

**Comment by lakshmantgld** [comment]
Anyone can explain me, which test is failing. I dont understand. I just added an line

**Comment by piotr-zuralski** [comment]
due to #598 as you could see that also in travis build https://travis-ci.org/enaqx/awesome-react/builds/209631903 
```
Issues :-(
> Links 
  1. [L0648]  https://rnplay.org/ SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 
  2. [L0725] 404 http://jamesfriend.com.au/implementing-flux-coffeescript  
```

**Comment by lakshmantgld** [comment]
Gotcha!! There are too many PRs waiting in the line...

**Comment by piotr-zuralski** [comment]
@lakshmantgld rebase your branch

**Pull request merged**
