### PR TITLE
Add mxstbr/react-boilerplate

### PR DESCRIPTION
**Pull request by mxstbr**

### CODE REVIEW

**Comment by browniefed** [comment]
Can you rebase please and then I'll merge, thanks.

**Comment by mxstbr** [comment]
Sorry, how do you want me to rebase?

**Comment by browniefed** [comment]
Ah sorry, it isn't currently mergeable, so just making it mergeable would be great!

**Comment by mxstbr** [comment]
New, mergeable PR: #353!

**Pull request closed without merging**
