### PR TITLE
add react.js tutorial for beginners

### PR DESCRIPTION
**Pull request by mrblueblue**
I added a tutorial ["React.js Introduction For People Who Know Just Enough jQuery To Get By."](http://reactfordesigners.com/labs/reactjs-introduction-for-people-who-know-just-enough-jquery-to-get-by/)

It leads you through step-by-step how to create a "Tweet Box" and is aimed at beginners who understand the basics of jQuery.

### CODE REVIEW

**Comment by chibicode** [comment]
@mrblueblue the author here - thank you!

**Comment by mrblueblue** [comment]
No problem, thanks for writing it!

**Comment by enaqx** [comment]
Thanks! Great article! :watermelon:

**Comment by chibicode** [comment]
@enaqx thanks!

**Pull request merged**
