### PR TITLE
Adding the React Testing Cookbook video lessons

### PR DESCRIPTION
**Pull request by trevordmiller**

### CODE REVIEW

**Comment by browniefed** [comment]
Hmm I wonder why the CI isn't running. To add duplicate links they need to be added to the `.travis.yml`

**Comment by trevordmiller** [comment]
@browniefed I'm sorry, I don't understand - what do you need me to do to get the CI to run?

**Comment by browniefed** [comment]
Hmm it should just automatically run, not sure why it isn't running. I'll go ahead and merge this and take care of things if the build fails with duplicate the duplicate link check. 
Thanks!

**Comment by trevordmiller** [comment]
@browniefed Thanks!

**Pull request merged**
